### ISSUE TITLE
Documentation about "What to expect when you put Terms of Use on a project or data folder?"

### ISSUE THREAD

**Issue by jaybee84** [nf-osi/nf-osi.github.io#5]
Re: Folders with "Request Access" 

Whenever a data folder or project goes under the ACT, everyone on that project or folder including the studyLead has to go through all the steps to request access to their own folders. I dont think this expectation has been outlined in any of the governance documentation. 

We should add this in the documentation for Synapse/Portals, and ideally should be a part of an email that goes to the studyLead when one of their data folders goes under ACT. 

Filing this issue here, but let me know if this may be more appropriate elsewhere :)

**Comment by kthrog** [comment]
This is a great idea, thanks for filling this, Jineta!
